#include "../../include/debug.h"
#include "../../include/pokemon.h"
#include "../../include/save.h"
#include "../../include/script.h"
#include "../../include/types.h"
#include "../../include/constants/item.h"

#ifdef MART_EXPANSION

struct MartItem {
    u16 item_id;
    u16 override_cost;
};

struct BadgeMartItems {
    u16 item_id;
    u8 required_badges;
};

// note: limited to 203 items (~34 pages)
const struct BadgeMartItems sBadgeMart[] = {
    { ITEM_POKE_BALL,      0 },
    { ITEM_GREAT_BALL,     3 },
    { ITEM_ULTRA_BALL,     5 },
    { ITEM_POTION,         0 },
    { ITEM_SUPER_POTION,   1 },
    { ITEM_HYPER_POTION,   5 },
    { ITEM_MAX_POTION,     7 },
    { ITEM_FULL_RESTORE,   8 },
    { ITEM_REVIVE,         3 },
    { ITEM_ANTIDOTE,       0 },
    { ITEM_PARALYZE_HEAL,  0 },
    { ITEM_AWAKENING,      1 },
    { ITEM_BURN_HEAL,      1 },
    { ITEM_ICE_HEAL,       1 },
    { ITEM_FULL_HEAL,      5 },
    { ITEM_ESCAPE_ROPE,    1 },
    { ITEM_REPEL,          1 },
    { ITEM_SUPER_REPEL,    3 },
    { ITEM_MAX_REPEL,      5 },
};

void LONG_CALL InitMartUI(void *taskManager, FieldSystem *fieldSystem, const u16 *items, int kind, int buySell, int decoWhich, const struct MartItem *priceOverrides);

u16 sCherrygroveCityMart[] = {
    ITEM_GRASS_MAIL, ITEM_FLAME_MAIL, ITEM_BUBBLE_MAIL, ITEM_BLOOM_MAIL, ITEM_TUNNEL_MAIL, ITEM_STEEL_MAIL, ITEM_HEART_MAIL, ITEM_SNOW_MAIL, ITEM_SPACE_MAIL, ITEM_AIR_MAIL, ITEM_MOSAIC_MAIL, ITEM_BRICK_MAIL, 0xFFFF
};

u16 sVioletCityMart[] = {
    ITEM_ZOOM_LENS, ITEM_WIDE_LENS, ITEM_SCOPE_LENS, 0xFFFF
};

u16 sAzaleaCityMart[] = {
    ITEM_IRON_BALL, ITEM_LAGGING_TAIL, ITEM_FLOAT_STONE, 0xFFFF
};

u16 sGoldenrodDepartmentUpper2F[] = {
    ITEM_GRASSY_SEED, ITEM_PSYCHIC_SEED, ITEM_ELECTRIC_SEED, ITEM_MISTY_SEED, ITEM_TERRAIN_EXTENDER, ITEM_SMOOTH_ROCK, ITEM_ICY_ROCK, ITEM_DAMP_ROCK, ITEM_HEAT_ROCK, ITEM_UTILITY_UMBRELLA, ITEM_SAFETY_GOGGLES, 0xFFFF
};

u16 sGoldenrodDepartmentLower2F[] = {
    ITEM_HP_UP, ITEM_PROTEIN, ITEM_IRON, ITEM_CALCIUM, ITEM_ZINC, ITEM_CARBOS, ITEM_POWER_WEIGHT, ITEM_POWER_BRACER, ITEM_POWER_BELT, ITEM_POWER_LENS, ITEM_POWER_BAND, ITEM_POWER_ANKLET, 0xFFFF
};

u16 sGoldenrodDepartment3F[] = {
    ITEM_LIECHI_BERRY, ITEM_GANLON_BERRY, ITEM_SALAC_BERRY, ITEM_PETAYA_BERRY, ITEM_APICOT_BERRY, ITEM_LANSAT_BERRY, ITEM_MICLE_BERRY, ITEM_KEE_BERRY, ITEM_MARANGA_BERRY, 0xFFFF
};

u16 sGoldenrodDepartment4F[] = {
    ITEM_CHERI_BERRY, ITEM_CHESTO_BERRY, ITEM_PECHA_BERRY, ITEM_RAWST_BERRY, ITEM_ASPEAR_BERRY, ITEM_PERSIM_BERRY, ITEM_ORAN_BERRY, ITEM_SITRUS_BERRY, 0xFFFF
};

u16 sGoldenrodDepartment5F[] = {
    ITEM_SUN_STONE, ITEM_MOON_STONE, ITEM_FIRE_STONE, ITEM_THUNDER_STONE, ITEM_WATER_STONE, ITEM_LEAF_STONE, ITEM_ICE_STONE, ITEM_SHINY_STONE, ITEM_DAWN_STONE, ITEM_DUSK_STONE, ITEM_OVAL_STONE, ITEM_EVERSTONE, 0xFFFF
};

//ITEM_TM070, ITEM_TM017, ITEM_TM054, ITEM_TM083, ITEM_TM016,ITEM_TM033, ITEM_TM022, ITEM_TM052, ITEM_TM038, ITEM_TM025,ITEM_TM014, ITEM_TM015
//ITEM_TM021, ITEM_TM027, ITEM_TM087, ITEM_TM078, ITEM_TM012, ITEM_TM041, ITEM_TM020, ITEM_TM028, ITEM_TM076, ITEM_TM055, ITEM_TM072, ITEM_TM079
	
u16 sGoldenrodHerbs[] = {
    ITEM_HEAL_POWDER, ITEM_ENERGY_POWDER, ITEM_ENERGY_ROOT, ITEM_REVIVAL_HERB, ITEM_WHITE_HERB, ITEM_MENTAL_HERB, ITEM_MIRROR_HERB, ITEM_POWER_HERB, 0xFFFF
};

u16 sEcruteakMart[] = {
    ITEM_ABSORB_BULB, ITEM_LUMINOUS_MOSS, ITEM_SNOWBALL, ITEM_CELL_BATTERY, 0xFFFF
};

u16 sOlivineMart[] = {
    ITEM_FLAME_ORB, ITEM_TOXIC_ORB, ITEM_STICKY_BARB, ITEM_BLACK_SLUDGE, 0xFFFF
};

u16 sCianwoodPharmacy[] = {
    ITEM_OCCA_BERRY, ITEM_PASSHO_BERRY, ITEM_WACAN_BERRY, ITEM_RINDO_BERRY, ITEM_YACHE_BERRY, ITEM_CHOPLE_BERRY, ITEM_KEBIA_BERRY, ITEM_SHUCA_BERRY, ITEM_COBA_BERRY, ITEM_PAYAPA_BERRY, ITEM_TANGA_BERRY, ITEM_CHARTI_BERRY, ITEM_KASIB_BERRY, ITEM_HABAN_BERRY, ITEM_COLBUR_BERRY, ITEM_BABIRI_BERRY, ITEM_CHILAN_BERRY, ITEM_ROSELI_BERRY, ITEM_ENIGMA_BERRY, 0xFFFF
};

u16 sBlackthornAndBattleFrontierMart[] = {
    ITEM_LUCKY_EGG, ITEM_SOOTHE_BELL, ITEM_RING_TARGET, ITEM_SHED_SHELL, 0xFFFF
};

u16 sIndigoPlateau[] = {
    ITEM_ULTRA_BALL, ITEM_MAX_REPEL, ITEM_HYPER_POTION, ITEM_MAX_POTION, ITEM_FULL_HEAL, ITEM_FULL_RESTORE,
    ITEM_REVIVE, ITEM_MAX_REVIVE, ITEM_ELIXIR, ITEM_MAX_ELIXIR, 0xFFFF
};

u16 sVermilionAndSafariMart[] = {
    ITEM_GALARICA_CUFF, ITEM_GALARICA_WREATH, ITEM_DEEP_SEA_SCALE, ITEM_DEEP_SEA_TOOTH, ITEM_PRISM_SCALE, ITEM_REAPER_CLOTH, ITEM_DUBIOUS_DISC, ITEM_PEAT_BLOCK, 0xFFFF
};

u16 sSaffronMart[] = {
    ITEM_THROAT_SPRAY, ITEM_PUNCHING_GLOVE, ITEM_LOADED_DICE, ITEM_BINDING_BAND, ITEM_GRIP_CLAW, ITEM_QUICK_CLAW, 0xFFFF
};

u16 sLavenderMart[] = {
    ITEM_EXPERT_BELT, ITEM_MUSCLE_BAND, ITEM_FOCUS_BAND, ITEM_SHELL_BELL, ITEM_WEAKNESS_POLICY, ITEM_BLUNDER_POLICY, 0xFFFF
};

u16 sCeruleanMart[] = {
    ITEM_CLEAR_AMULET, ITEM_PROTECTIVE_PADS, ITEM_ABILITY_SHIELD, ITEM_ADRENALINE_ORB, ITEM_ROOM_SERVICE, ITEM_METRONOME,  0xFFFF
};

u16 sCeladonDepartmentUpper2F[] = { //LEFT
    ITEM_X_SPEED, ITEM_X_ATTACK, ITEM_X_DEFENSE, ITEM_GUARD_SPEC, ITEM_DIRE_HIT, ITEM_X_ACCURACY, ITEM_X_SP_ATK, ITEM_X_SP_DEF, ITEM_PP_UP, ITEM_MACHO_BRACE, ITEM_EXP_SHARE, 0xFFFF
};

u16 sCeladonDepartmentLower2F[] = { //RIGHT
    ITEM_FULL_INCENSE, ITEM_LAX_INCENSE, ITEM_LUCK_INCENSE, ITEM_ODD_INCENSE, ITEM_PURE_INCENSE, ITEM_ROCK_INCENSE, ITEM_ROSE_INCENSE, ITEM_SEA_INCENSE, ITEM_WAVE_INCENSE, ITEM_DESTINY_KNOT, ITEM_MIRROR_HERB, ITEM_LIGHT_BALL, 0xFFFF
};

u16 sCeladonDepartment3F[] = {
    ITEM_KINGS_ROCK, ITEM_RAZOR_FANG, ITEM_RAZOR_CLAW, ITEM_BLACK_AUGURITE, ITEM_METAL_COAT, ITEM_DRAGON_SCALE, ITEM_UP_GRADE, ITEM_PROTECTOR, ITEM_MAGMARIZER, ITEM_ELECTIRIZER, ITEM_LINKING_CORD, ITEM_RARE_CANDY, 0xFFFF
};

u16 sCeladonDepartment4F[] = {
    ITEM_POKE_BALL, ITEM_GREAT_BALL, ITEM_ULTRA_BALL, ITEM_DUSK_BALL, ITEM_HEAL_BALL, ITEM_QUICK_BALL, ITEM_NET_BALL, ITEM_DIVE_BALL, ITEM_NEST_BALL, ITEM_REPEAT_BALL, ITEM_TIMER_BALL, ITEM_LUXURY_BALL, ITEM_PREMIER_BALL, ITEM_CHERISH_BALL, ITEM_SAFARI_BALL, ITEM_SPORT_BALL, ITEM_PARK_BALL, ITEM_DREAM_BALL, ITEM_BEAST_BALL, ITEM_STRANGE_BALL, 0xFFFF
};

u16 sCeladonDepartmentLeft5F[] = {
    ITEM_CUSTAP_BERRY, ITEM_ROWAP_BERRY, ITEM_JABOCA_BERRY, ITEM_HEALTH_FEATHER, ITEM_MUSCLE_FEATHER, ITEM_RESIST_FEATHER, ITEM_GENIUS_FEATHER, ITEM_CLEVER_FEATHER, ITEM_SWIFT_FEATHER, ITEM_PRETTY_FEATHER, 0xFFFF
};

u16 sCeladonDepartmentRight5F[] = {
    ITEM_LONELY_MINT, ITEM_ADAMANT_MINT, ITEM_NAUGHTY_MINT, ITEM_BRAVE_MINT, ITEM_BOLD_MINT, ITEM_IMPISH_MINT, ITEM_LAX_MINT, ITEM_RELAXED_MINT, ITEM_MODEST_MINT, ITEM_MILD_MINT, ITEM_RASH_MINT, ITEM_QUIET_MINT, ITEM_CALM_MINT, ITEM_GENTLE_MINT, ITEM_CAREFUL_MINT, ITEM_SASSY_MINT, ITEM_TIMID_MINT, ITEM_HASTY_MINT, ITEM_JOLLY_MINT, ITEM_NAIVE_MINT, ITEM_SERIOUS_MINT,	0xFFFF
};

u16 sFuschiaMart[] = {
    ITEM_EVIOLITE, ITEM_LEFTOVERS, ITEM_LUM_BERRY, ITEM_HEAVY_DUTY_BOOTS, ITEM_COVERT_CLOAK, ITEM_BRIGHT_POWDER, 0xFFFF
};

u16 sPewterMart[] = {
    ITEM_EJECT_PACK, ITEM_EJECT_BUTTON, ITEM_RED_CARD, ITEM_ASSAULT_VEST, ITEM_ROCKY_HELMET, ITEM_FOCUS_SASH, 0xFFFF
};

u16 sViridianMart[] = {
    ITEM_CHOICE_BAND, ITEM_CHOICE_SPECS, ITEM_CHOICE_SCARF, ITEM_LIFE_ORB, ITEM_LIGHT_CLAY, ITEM_AIR_BALLOON, 0xFFFF
};

u16 sMtMoonSquare[] = {
    ITEM_TM001, ITEM_TM002, ITEM_TM003, ITEM_TM004, ITEM_TM005, ITEM_TM006, ITEM_TM007, ITEM_TM008, ITEM_TM009, ITEM_TM010, ITEM_TM011, ITEM_TM012, ITEM_TM013, ITEM_TM014, ITEM_TM015, ITEM_TM016, ITEM_TM017, ITEM_TM018, ITEM_TM019, ITEM_TM020, ITEM_TM021, ITEM_TM022, ITEM_TM023, ITEM_TM024, ITEM_TM025, ITEM_TM026, ITEM_TM027, ITEM_TM028, ITEM_TM029, ITEM_TM030, ITEM_TM031, ITEM_TM032, ITEM_TM033, ITEM_TM034, ITEM_TM035, ITEM_TM036, ITEM_TM037, ITEM_TM038, ITEM_TM039, ITEM_TM040, ITEM_TM041, ITEM_TM042, ITEM_TM043, ITEM_TM044, ITEM_TM045, ITEM_TM046, ITEM_TM047, ITEM_TM048, ITEM_TM049, ITEM_TM050, ITEM_TM051, ITEM_TM052, ITEM_TM053, ITEM_TM054, ITEM_TM055, ITEM_TM056, ITEM_TM057, ITEM_TM058, ITEM_TM059, ITEM_TM060, ITEM_TM061, ITEM_TM062, ITEM_TM063, ITEM_TM064, ITEM_TM065, ITEM_TM066, ITEM_TM067, ITEM_TM068, ITEM_TM069, ITEM_TM070, ITEM_TM071, ITEM_TM072, ITEM_TM073, ITEM_TM074, ITEM_TM075, ITEM_TM076, ITEM_TM077, ITEM_TM078, ITEM_TM079, ITEM_TM080, ITEM_TM081, ITEM_TM082, ITEM_TM083, ITEM_TM084, ITEM_TM085, ITEM_TM086, ITEM_TM087, ITEM_TM088, ITEM_TM089, ITEM_TM090, ITEM_TM091, ITEM_TM092, 0xFFFF
};

u16 sMahoganyPreRocketHideout[] = {
    ITEM_TINY_MUSHROOM, ITEM_NUGGET, ITEM_BIG_PEARL, 0xFFFF
};

u16 sMahoganyPostRocketHideout[] = {
    ITEM_POMEG_BERRY, ITEM_KELPSY_BERRY, ITEM_QUALOT_BERRY, ITEM_HONDEW_BERRY, ITEM_GREPA_BERRY, ITEM_TAMATO_BERRY, ITEM_ABILITY_PATCH, ITEM_ABILITY_CAPSULE, 0xFFFF
};

BOOL ScrCmd_MartBuy(SCRIPTCONTEXT *ctx) {
    u16 unused UNUSED = ScriptGetVar(ctx);
    
    u16 items[NELEMS(sBadgeMart) + 1];
    u8 badgeCount = 0;
    u8 index = 0;
    u32 i;

    for (i = 0; i < 16; i++) {
        if (PlayerProfile_TestBadgeFlag(Sav2_PlayerData_GetProfileAddr(ctx->fsys->savedata), i) == TRUE) {
            badgeCount++;
        }
    }

    for (i = 0; i < NELEMS(sBadgeMart); i++) {
        if (badgeCount >= sBadgeMart[i].required_badges) {
            items[index] = sBadgeMart[i].item_id;
            index++;
        }
    }

    items[index] = 0xFFFF;
    InitMartUI(ctx->taskman, ctx->fsys, items, 0, 0, 0, 0); // this doesn't honor price overrides
    return TRUE;
}

#endif // MART_EXPANSION

#ifdef POKEATHLON_SHOP_EXPANSION

const struct MartItem sPokeathlonShopSunday[] = {
    { ITEM_RED_APRICORN,   200  },
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_BLACK_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_KINGS_ROCK,     3000 },
    { ITEM_HEART_SCALE,    1000 },
    { ITEM_FULL_RESTORE,   500  },
    { ITEM_NUGGET,         500  },
    { ITEM_SUN_STONE,      3000 },
    { ITEM_FIRE_STONE,     2500 },
    { ITEM_SHINY_STONE,    3000 },
    { ITEM_DAWN_STONE,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopMonday[] = {
    { ITEM_RED_APRICORN,   200  },
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_GREEN_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_MOON_STONE,     3000 },
    { ITEM_RARE_CANDY,     2000 },
    { ITEM_FULL_RESTORE,   500  },
    { ITEM_KINGS_ROCK,     3000 },
    { ITEM_SUN_STONE,      3000 },
    { ITEM_WATER_STONE,    2500 },
    { ITEM_SHINY_STONE,    3000 },
    { ITEM_DUSK_STONE,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopTuesday[] = {
    { ITEM_YELLOW_APRICORN, 200  },
    { ITEM_PINK_APRICORN,   200  },
    { ITEM_WHITE_APRICORN,  200  },
    { ITEM_MOOMOO_MILK,     100  },
    { ITEM_FIRE_STONE,      2500 },
    { ITEM_PP_UP,           1000 },
    { ITEM_FULL_RESTORE,    500  },
    { ITEM_METAL_COAT,      2500 },
    { ITEM_WATER_STONE,     2500 },
    { ITEM_LEAF_STONE,      2500 },
    { ITEM_DUSK_STONE,      3000 },
    { ITEM_DAWN_STONE,      3000 },
    { 0xFFFF,               0    },
};

const struct MartItem sPokeathlonShopWednesday[] = {
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_PINK_APRICORN,  200  },
    { ITEM_BLACK_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_WATER_STONE,    2500 },
    { ITEM_HEART_SCALE,    1000 },
    { ITEM_FULL_RESTORE,   500  },
    { ITEM_DRAGON_SCALE,   2500 },
    { ITEM_THUNDER_STONE,  2500 },
    { ITEM_MOON_STONE,     3000 },
    { ITEM_SHINY_STONE,    3000 },
    { ITEM_DAWN_STONE,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopThursday[] = {
    { ITEM_YELLOW_APRICORN, 200  },
    { ITEM_PINK_APRICORN,   200  },
    { ITEM_WHITE_APRICORN,  200  },
    { ITEM_MOOMOO_MILK,     100  },
    { ITEM_THUNDER_STONE,   2500 },
    { ITEM_PP_UP,           1000 },
    { ITEM_FULL_RESTORE,    500  },
    { ITEM_KINGS_ROCK,      3000 },
    { ITEM_FIRE_STONE,      2500 },
    { ITEM_LEAF_STONE,      2500 },
    { ITEM_SHINY_STONE,     3000 },
    { ITEM_DUSK_STONE,      3000 },
    { 0xFFFF,               0    },
};

const struct MartItem sPokeathlonShopFriday[] = {
    { ITEM_RED_APRICORN,    200  },
    { ITEM_YELLOW_APRICORN, 200  },
    { ITEM_GREEN_APRICORN,  200  },
    { ITEM_MOOMOO_MILK,     100  },
    { ITEM_METAL_COAT,      2500 },
    { ITEM_NUGGET,          500  },
    { ITEM_FULL_RESTORE,    500  },
    { ITEM_DRAGON_SCALE,    2500 },
    { ITEM_WATER_STONE,     2500 },
    { ITEM_SUN_STONE,       3000 },
    { ITEM_DUSK_STONE,      3000 },
    { ITEM_DAWN_STONE,      3000 },
    { 0xFFFF,               0    },
};

const struct MartItem sPokeathlonShopSaturday[] = {
    { ITEM_GREEN_APRICORN,  200  },
    { ITEM_WHITE_APRICORN,  200  },
    { ITEM_BLACK_APRICORN,  200  },
    { ITEM_MOOMOO_MILK,     100  },
    { ITEM_LEAF_STONE,      2500 },
    { ITEM_RARE_CANDY,      2000 },
    { ITEM_FULL_RESTORE,    500  },
    { ITEM_METAL_COAT,      2500 },
    { ITEM_THUNDER_STONE,   2500 },
    { ITEM_SHINY_STONE,     3000 },
    { ITEM_DUSK_STONE,      3000 },
    { ITEM_DAWN_STONE,      3000 },
    { 0xFFFF,               0    },
};

#endif // POKEATHLON_SHOP_EXPANSION
